version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  django:
    build: .
    volumes:
      - ./todoapp/:/app/todoapp
    env_file:
      - .env
    ports:
      - 8010:8000
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A sampleproject worker -l info
    volumes:
      - ./todoapp/:/app/todoapp
    env_file:
      - .env
    depends_on:
      - redis
      - django